### ISSUE TITLE
[1h] Shortcode presentation - Contact

### ISSUE THREAD

**Issue by zufrieden** [epfl-idevelop/wp-theme-2018#11]

**Comment by jdelasoie** [comment]
Cette PR https://github.com/epfl-idevelop/wp-theme-2018/pull/108/files résout-elle cette issue ? Elle concerne le shortcode epfl_contact, qui rend le contact banner de cette page https://epfl-idevelop.github.io/elements/#/organisms/contact

**Comment by zufrieden** [comment]
Yes
