### ISSUE TITLE
Augmenter la robustesse pour l'API de Memento -> visual_url

### ISSUE THREAD

**Issue by obieler** [epfl-idevelop/wp-theme-2018#168]
Les changements d'url aux endroits suivants ne survivraient pas à un changement d'extension ou de dimension d'image (ex. 1440x810, un caractère en trop pour le substring):
* https://github.com/epfl-idevelop/wp-theme-2018/blob/1ef9341158234cd5e561a7e9faee7258be56036a/shortcodes/epfl_memento/view.php#L156 
* https://github.com/epfl-idevelop/wp-theme-2018/blob/1ef9341158234cd5e561a7e9faee7258be56036a/shortcodes/epfl_memento/templates/card-img-top.php#L6

En lien -> [INC0266178](https://it.epfl.ch/backoffice/nav_to.do?uri=incident.do?sys_id=45a04d6fdb7eef44914f9ec4db96197c)

**Comment by LuluTchab** [comment]
De plus, il faut check si le `->visual_url` est `NULL` ou pas. CF [INC0272030](https://support.epfl.ch/backoffice/nav_to.do?uri=incident.do%3Fsys_id=a15aa826dbeb674032ea9085db96192b%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true)

Actuellement, sur Firefox, en bas de la page https://www.epfl.ch/education/fr/education/, quand `->visual_url` est à `NULL`, le lien sur l'image à afficher est foireux et ça affiche une image "brisée":
![image](https://user-images.githubusercontent.com/11942430/52775014-f2230e00-303e-11e9-9c50-8a52477cd5d4.png)

Le shortcode utilisé est le suivant : `[epfl_memento_2018 memento="academic-calendar" template="3" lang="fr" /]`

Il faudra définir avec @lvenries ce qu'on fait comme correction exactement
- Pas d'image?
- Image "vide" (ou remplacée par un `<div>` aux bonnes dimensions pour ne rien casser)
- Image pour dire qu'il n'y a pas d'illustration (logo EPFL par ex)

**Comment by jdelasoie** [comment]
Les deux tickets Snow mentionnés sont fermés, je ferme le ticket.
