### ISSUE TITLE
Traductions manquantes pour la recherche

### ISSUE THREAD

**Issue by williambelle** [epfl-idevelop/wp-theme-2018#199]
Desktop:

https://github.com/epfl-idevelop/wp-theme-2018/blob/99e4f501635d22a78f7a606613479615f38dfd7f/header.php#L154-L156

Mobile:

https://github.com/epfl-idevelop/wp-theme-2018/blob/99e4f501635d22a78f7a606613479615f38dfd7f/header.php#L168-L169

![search](https://user-images.githubusercontent.com/2843501/56356531-631aa980-61d9-11e9-8884-fb355ddd3dfb.png)

**Comment by jdelasoie** [comment]
Corrigé avec cette PR https://github.com/epfl-idevelop/wp-theme-2018/pull/212

Merci
