### ISSUE TITLE
Breadcrumb vide

### ISSUE THREAD

**Issue by lvenries** [epfl-idevelop/wp-theme-2018#38]

**Comment by lvenries** [comment]
Hello,
Nous avons déployé le thème version 1.0.0. Le Breadcrum est complètement vide quelque soit le niveau de la de la pga eou nous nous trouvons. Il y a que la petite maison Home d'affiché

**Comment by zufrieden** [comment]
https://github.com/epfl-idevelop/elements/issues/246

**Comment by zufrieden** [comment]
Related to https://github.com/epfl-idevelop/elements/issues/208 too

**Comment by knuch** [comment]
Correctif mis en place dans 9e2e187e26f73907eafc2b693c406ae064b4b9dd . Sera posté dans la prochaine release.
Test disponible sur https://migration-wp.epfl.ch/styleguide-qa/

**Comment by zufrieden** [comment]
Pour faire suite à ton message @lvenries concernant le menu, le breadcrumb et browse.

J'ai encore re-testé de mon coté et ça fonctionne parfaitement. Est-ce que tu défini bien le menu comme menu principal ? Voir la print-screen ci-joint : 

![epfl_wp_menu_check](https://user-images.githubusercontent.com/451236/44707653-683db380-aaa5-11e8-9b16-4b62d9f6d7ac.gif)

**Comment by zufrieden** [comment]
Fixed ;-)
