### ISSUE TITLE
Afficher le bon numéro de version du thème

### ISSUE THREAD

**Issue by GregLeBarbar** [epfl-idevelop/wp-theme-2018#46]
Lorsque nous sommes dans le dashboard de WordPress dans la gestion des thèmes, on ne voit pas le bon numéro de version car vous mettez le numéro de version dans un fichier VERSION séparé et pas dans le style.css 

Pouvez vous svp changer cela pour que l'"utilisateur" puisse voir le bon numéro de version du thème directement dans le dashboard?

Merci et bonne journée :-)

**Comment by jdelasoie** [comment]
Je ferme le ticket, ce n'est plus un problème
