### ISSUE TITLE
Styleguide 1.2.1

### ISSUE THREAD

**Issue by knuch** [epfl-idevelop/wp-theme-2018#69]
la release 1.2.1 du styleguide est disponible:
https://github.com/epfl-idevelop/elements/tree/dist/frontend
(attention, il faut de nouveau nettoyer les images en trop. j'ai créé une issue pour ce souci https://github.com/epfl-idevelop/elements/issues/278)

**Comment by GregLeBarbar** [comment]
Cette release à été intégrée avec la release du thème  1.2.2
