### ISSUE TITLE
Homepage devrait se comporter comme les template Aside

### ISSUE THREAD

**Issue by lvenries** [epfl-idevelop/wp-theme-2018#82]
Une homepage defini au niveau du site devtrait se comporter comme le template Aside none ou les autres et non comme le template Homepage. Sur les instance de niveau 1 et 2 et nous aurrons des homepage et elles doivent avoir le breadcrum et le bouton browse.
La seule page qui aura le template Homepage sans braedcrum sera la homepage de www.epfl.ch

**Comment by zufrieden** [comment]
Nous en avons discuté lors de notre séance du 21 août. (cf https://3.basecamp.com/3096442/buckets/5137241/documents/1266489218)

**La décision alors :**
Étant donné que la homepage d'une instance wordpress peut potentiellement se retrouver à tous les niveau, nous n'avons pas de comportement spécifique pour la homepage (au sens frontpage.php). Nous avons donc créé un layout de page "homepage" qui se comporte comme demandé : pas de fil d'ariane, pas de browse, pas de menu à gauche.

Ce système donne la plus grande souplesse.

**Comment by lvenries** [comment]
Oui c'est exactement cela que nous voulons, mais ce n'est pas ce qui se passe avec la version 1.4.2 du thème.
Si nous mettons au niveau du site dans Settings => Reading => A static page qui a le template Aside, elle va s'affciher comme avec template Homepage sans Breadcrum et bouton browse.
C'est donc bien un bug.

**Comment by zufrieden** [comment]
Yep, bien vu.

- [ ] Sur une homepage (défini au sens Réglage, lecture, homepage static), lorsqu'on sélectionne le layout aside*, la page s'affiche comme décrit par le layout.
- [ ]
